# 📘 E2E ETL Validation — Complete Study Notes
### Project: SQL Server → ADF → ADLS Bronze → Databricks → Silver → Gold
### Includes: All Code + All Doubts Explained

---

## 🗺️ Pipeline Architecture

```
SQL Server (Source)
      ↓
ADF Copy Activity  →  ADLS Gen2 Bronze (Parquet)
      ↓
      ADF captures output automatically:
      { "rowsCopied": 7, "rowsRead": 7, "filesWritten": 1 }
      ↓
ADF Notebook Activity  →  Databricks Bronze Validation Notebook
      (passes rowsCopied as parameter)
      ↓
ADF If Condition  →  reads notebook exit value
      ↓                        ↓
   SUCCESS               FAILED
      ↓                        ↓
Silver Notebook         Alert / Stop Pipeline
      ↓
Gold Notebook
      ↓
Power BI / Reports
```

---

## 💡 DOUBT 1 — How Does ADF Know How Many Rows Were Copied?

```
┌─────────────────────────────────────────────────────────┐
│  ADF Copy Activity = A Delivery Truck                   │
│                                                         │
│  Truck delivers 7 boxes    → rowsCopied = 7             │
│  Warehouse counts 7 boxes  → actual_rows = 7            │
│  ✅ Delivery confirmed!                                 │
│                                                         │
│  Truck says 7 but only 5 arrive → 🚨 MISMATCH          │
└─────────────────────────────────────────────────────────┘
```

### ADF Copy Activity Output JSON (auto-generated by ADF):
```json
{
    "dataRead": 2048,
    "dataWritten": 1536,
    "filesWritten": 1,
    "rowsRead": 7,
    "rowsCopied": 7,
    "copyDuration": 4,
    "throughput": 0.5,
    "errors": []
}
```

> You do NOT calculate this yourself.
> ADF generates this automatically after every Copy Activity run.
> You can see it by clicking the Output icon on Copy Activity in ADF.

---

## 💡 DOUBT 2 — How To Pass rowsCopied To Databricks Notebook?

### In ADF — Notebook Activity → Parameters Tab:

```
Parameter Name    │  Value (ADF Dynamic Expression)
──────────────────┼──────────────────────────────────────────────
adf_row_count     │  @activity('CopyActivity').output.rowsCopied
run_date          │  @formatDateTime(utcnow(),'yyyy-MM-dd')
```

> @activity('CopyActivity').output.rowsCopied
> This is an ADF dynamic expression.
> It reads the output of your Copy Activity automatically.
> 'CopyActivity' = the exact name you gave your Copy Activity in ADF.

### ADF Pipeline Flow:

```
[Copy Activity]
      ↓
   output.rowsCopied = 7   ← ADF stores this automatically
      ↓
[Notebook Activity]
   Parameters:
   adf_row_count = @activity('CopyActivity').output.rowsCopied
      ↓
[Databricks Notebook]
   Receives adf_row_count = 7
```

---

## 💡 DOUBT 3 — How Does dbutils.widgets Work?

```
dbutils.widgets = the POST BOX between ADF and Databricks

ADF puts values in the post box (via Parameters tab)
Databricks reads values from the post box (via widgets.get)
```

```python
# STEP 1: Declare the widget (create the post box + set default)
# "0" and "" are DEFAULT values if ADF doesn't pass anything
dbutils.widgets.text("adf_row_count", "0")
dbutils.widgets.text("run_date", "")

# STEP 2: Read the value ADF put in
adf_row_count = int(dbutils.widgets.get("adf_row_count"))
run_date      = dbutils.widgets.get("run_date")

# int() converts "7" (string) → 7 (integer) for comparison

print(f"ADF told us it copied : {adf_row_count} rows")
print(f"Run date              : {run_date}")
```

---

## 📦 Master Sample Dataset

```python
from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, sum as spark_sum, count, avg,
    round as spark_round, lit, when,
    current_timestamp, to_date, to_timestamp,
    row_number, desc
)
from pyspark.sql.types import DoubleType, IntegerType
from pyspark.sql.window import Window

spark = SparkSession.builder.appName("E2E_Validation").getOrCreate()

raw_orders = [
    # order_id, cust_id, product,     amount,  order_date,   status,     region,  updated_dt
    (1001, "C001", "Sensor_Kit",  4500.00, "2024-01-15", "COMPLETED", "NORTH", "2024-01-15 08:00:00"),
    (1002, "C002", "Motor_Unit",  8200.00, "2024-01-15", "COMPLETED", "SOUTH", "2024-01-15 09:00:00"),
    (1003, "C003", "Control_Box", 3100.00, "2024-01-15", "PENDING",   "EAST",  "2024-01-15 10:00:00"),
    (1004, "C001", "Sensor_Kit",  4500.00, "2024-01-15", "COMPLETED", "NORTH", "2024-01-15 08:00:01"),  # Duplicate
    (1005, "C004", "Drive_Unit",  None,    "2024-01-15", "COMPLETED", "WEST",  "2024-01-15 11:00:00"),  # Null amount
    (1006,  None,  "Motor_Unit",  6100.00, "2024-01-15", "COMPLETED", "SOUTH", "2024-01-15 12:00:00"),  # Null cust_id
    (1007, "C005", "Sensor_Kit", -500.00,  "2024-01-15", "COMPLETED", "NORTH", "2024-01-15 13:00:00"),  # Negative amt
]

order_cols = [
    "order_id", "cust_id", "product",
    "amount", "order_date", "status",
    "region", "updated_dt"
]

df_raw = spark.createDataFrame(raw_orders, order_cols)
df_raw.show(truncate=False)
```

### Output:
```
+--------+-------+-----------+-------+----------+---------+------+-------------------+
|order_id|cust_id|product    |amount |order_date|status   |region|updated_dt         |
+--------+-------+-----------+-------+----------+---------+------+-------------------+
|    1001|   C001|Sensor_Kit |4500.0 |2024-01-15|COMPLETED|NORTH |2024-01-15 08:00:00|
|    1002|   C002|Motor_Unit |8200.0 |2024-01-15|COMPLETED|SOUTH |2024-01-15 09:00:00|
|    1003|   C003|Control_Box|3100.0 |2024-01-15|PENDING  |EAST  |2024-01-15 10:00:00|
|    1004|   C001|Sensor_Kit |4500.0 |2024-01-15|COMPLETED|NORTH |2024-01-15 08:00:01| ← Duplicate
|    1005|   C004|Drive_Unit |null   |2024-01-15|COMPLETED|WEST  |2024-01-15 11:00:00| ← Null amount
|    1006|   null|Motor_Unit |6100.0 |2024-01-15|COMPLETED|SOUTH |2024-01-15 12:00:00| ← Null cust_id
|    1007|   C005|Sensor_Kit |-500.0 |2024-01-15|COMPLETED|NORTH |2024-01-15 13:00:00| ← Negative amt
+--------+-------+-----------+-------+----------+---------+------+-------------------+
```

---

## 🥉 STAGE 1 — Bronze Validation Notebook

```python
run_date   = "2024-01-15"
bronze_path = f"bronze/sales_orders/year=2024/month=01/day=15/"

# In real project:
# df_bronze = spark.read.parquet(bronze_path)
df_bronze = df_raw  # Using sample data here

validation_results = {}

print("=" * 55)
print("🥉 BRONZE VALIDATION REPORT")
print(f"   Run Date   : {run_date}")
print(f"   Bronze Path: {bronze_path}")
print("=" * 55)
```

---

### ✅ Check 1 — Row Count vs ADF Metadata

```python
# adf_row_count comes from ADF via dbutils.widgets (see Doubt 1,2,3)
adf_row_count = int(dbutils.widgets.get("adf_row_count"))
actual_rows   = df_bronze.count()
count_match   = adf_row_count == actual_rows

validation_results["row_count_check"] = count_match

print(f"\n📊 Check 1 — Row Count")
print(f"   ADF Reported : {adf_row_count}")
print(f"   Actual Rows  : {actual_rows}")
print(f"   Status       : {'✅ PASSED' if count_match else '🚨 FAILED'}")
```

---

### ✅ Check 2 — Critical Column Null Check

```python
# We only check columns that MUST never be null
# order_id, order_date, status are mandatory for pipeline to work
critical_cols   = ["order_id", "order_date", "status"]
null_check_pass = True

print(f"\n📊 Check 2 — Critical Column Nulls")
for c in critical_cols:
    null_cnt = df_bronze.filter(col(c).isNull()).count()
    status   = "✅" if null_cnt == 0 else "🚨"
    print(f"   {status} {c:15} → {null_cnt} nulls")
    if null_cnt > 0:
        null_check_pass = False

validation_results["null_check"] = null_check_pass
```

---

### ✅ Check 3 — Schema Check

```python
# ── What is set()? ──
# A set is a bag of unique items with no duplicates
# You can compare two sets to find differences

# Example:
# set(["apple","banana","apple"]) → {"apple","banana"}  no duplicates!

expected_cols = set(order_cols)          # Your blueprint — what SHOULD exist
actual_cols   = set(df_bronze.columns)   # Reality — what ACTUALLY arrived

# ── The minus operator between sets ──
# actual - expected = columns in actual but NOT in expected = NEW columns
# expected - actual = columns in expected but NOT in actual = MISSING columns

new_cols     = actual_cols - expected_cols
missing_cols = expected_cols - actual_cols
schema_match = expected_cols == actual_cols

validation_results["schema_check"] = schema_match

print(f"\n📊 Check 3 — Schema Consistency")
print(f"   New Columns     : {new_cols     if new_cols     else 'None'}")
print(f"   Missing Columns : {missing_cols if missing_cols else 'None'}")
print(f"   Status          : {'✅ PASSED' if schema_match else '🚨 FAILED'}")
```

### 💡 DOUBT 4 — set() Explained With All Scenarios

```python
# ── Scenario 1: Normal Day — Everything Matches ──
expected = {"order_id", "cust_id", "amount", "status"}
actual   = {"order_id", "cust_id", "amount", "status"}

print(actual - expected)    # set() → empty → no new columns
print(expected - actual)    # set() → empty → nothing missing
# ✅ Schema matches!

# ── Scenario 2: Source Added A Column ──
expected = {"order_id", "cust_id", "amount", "status"}
actual   = {"order_id", "cust_id", "amount", "status", "discount_pct"}

print(actual - expected)    # {'discount_pct'} → new column appeared!
print(expected - actual)    # set()            → nothing missing
# ⚠️ Source team added a column — check if downstream needs updating

# ── Scenario 3: Source Renamed A Column ──
expected = {"order_id", "cust_id", "amount", "status"}
actual   = {"order_id", "customer_id", "amount", "status"}
#                         ↑ renamed from cust_id!

print(actual - expected)    # {'customer_id'} → looks new
print(expected - actual)    # {'cust_id'}     → old name missing
# 🚨 Together: cust_id was RENAMED to customer_id — breaking change!
```

### Visual:
```
EXPECTED (Blueprint)          ACTUAL (Reality)
────────────────────          ────────────────
order_id        ←──────────→  order_id
cust_id         ←──────────→  cust_id
product         ←──────────→  product
amount          ←──────────→  amount
order_date      ←──────────→  order_date
status          ←──────────→  status
region          ←──────────→  region
updated_dt      ←──────────→  updated_dt
                              discount_pct  ← 🚨 EXTRA!

new_cols     = {discount_pct}  ← in actual, not in expected
missing_cols = {}              ← nothing missing
```

---

### ✅ Bronze Gate Decision

```python
all_passed = all(validation_results.values())

print("\n" + "=" * 55)
print(f"🏁 BRONZE GATE: {'✅ PROCEED TO SILVER' if all_passed else '🚨 HALT PIPELINE'}")
print("=" * 55)
```

---

## 💡 DOUBT 5 — How To Fail ADF Pipeline On Validation Failure?

### Method 1 — dbutils.notebook.exit() + ADF If Condition (More Control)

```python
# At the end of your Bronze Validation Notebook:

if all_passed:
    print("✅ All checks passed")
    dbutils.notebook.exit("SUCCESS")   # 🟢 Signal to ADF: all good
else:
    print(f"🚨 Validation failed")
    dbutils.notebook.exit("FAILED")    # 🔴 Signal to ADF: stop here
```

### In ADF — If Condition Activity Expression:
```
@equals(
    activity('Bronze_Validation').output.runOutput,
    'SUCCESS'
)

TRUE branch  → [Silver Notebook Activity]
FALSE branch → [Web Activity: Send Teams Alert]  OR  leave empty to stop
```

### ADF Pipeline Visual:
```
[Copy Activity]
      ↓
[Notebook Activity: Bronze_Validation]
   Returns "SUCCESS" or "FAILED"
      ↓
[If Condition]
   Is runOutput == 'SUCCESS'?
      ↓               ↓
   YES               NO
    ↓                 ↓
[Silver          [Fail Activity]
 Notebook]       or [Alert]
```

---

### Method 2 — raise Exception (Simpler)

```python
# Simpler approach — just crash the notebook
# ADF automatically marks Notebook Activity as FAILED
# No If Condition needed — downstream activities don't run

if not all_passed:
    raise Exception(f"🚨 Bronze Validation Failed: {failure_reason}")
```

### Which To Use?

```
Method 1: dbutils.notebook.exit() + If Condition
→ Use when you want custom branching
→ e.g., send Teams alert AND stop pipeline

Method 2: raise Exception()
→ Simpler — just stop, ADF handles failure email
→ Good for quick implementation
```

---

## 🥈 STAGE 2 — Silver Transformation + Validation

```python
df_input = df_bronze

print("=" * 55)
print("🥈 SILVER TRANSFORMATION + VALIDATION")
print("=" * 55)
```

### Step 1 — Deduplication

```python
# Window function: group by order_id, sort by latest updated_dt
# row_number = 1 means the LATEST record for each order_id
# This removes duplicate order 1004 (same order_id as 1001)

window_dedup = Window \
    .partitionBy("order_id") \
    .orderBy(desc("updated_dt"))

df_deduped = df_input \
    .withColumn("row_num", row_number().over(window_dedup)) \
    .filter(col("row_num") == 1) \
    .drop("row_num")

dupes_removed = df_input.count() - df_deduped.count()
print(f"\n🔄 Step 1: Deduplication")
print(f"   Input Rows    : {df_input.count()}")
print(f"   After Dedup   : {df_deduped.count()}")
print(f"   Dupes Removed : {dupes_removed}")
```

### Step 2 — Business Rule Validation + Quarantine

```python
# Tag each record with WHY it failed
# Records that pass ALL rules get "PASSED"
# Records that fail go to quarantine with failure reason

df_tagged = df_deduped.withColumn(
    "dq_status",
    when(col("cust_id").isNull(),  lit("FAIL_NULL_CUST_ID"))
    .when(col("amount").isNull(),   lit("FAIL_NULL_AMOUNT"))
    .when(col("amount") <= 0,       lit("FAIL_NEGATIVE_AMOUNT"))
    .when(
        ~col("status").isin(["COMPLETED", "PENDING", "CANCELLED"]),
        lit("FAIL_INVALID_STATUS")
    )
    .otherwise(lit("PASSED"))
)

# Split into two paths
df_silver_valid = df_tagged \
    .filter(col("dq_status") == "PASSED") \
    .drop("dq_status")

df_quarantine = df_tagged \
    .filter(col("dq_status") != "PASSED") \
    .withColumn("quarantine_ts", current_timestamp()) \
    .withColumn("pipeline_run_date", lit(run_date))

print(f"\n🔄 Step 2: Business Rule Validation")
print(f"   Total after dedup  : {df_deduped.count()}")
print(f"   ✅ Valid → Silver  : {df_silver_valid.count()}")
print(f"   🚨 Quarantined     : {df_quarantine.count()}")

print("\n✅ Valid Silver Records:")
df_silver_valid.show(truncate=False)

print("🚨 Quarantine Records:")
df_quarantine.select(
    "order_id", "cust_id", "amount", "dq_status"
).show(truncate=False)
```

### Step 3 — Type Casting + Schema Enforcement

```python
df_silver_final = df_silver_valid \
    .withColumn("amount",     col("amount").cast(DoubleType())) \
    .withColumn("order_date", to_date(col("order_date"), "yyyy-MM-dd")) \
    .withColumn("updated_dt", to_timestamp(col("updated_dt"))) \
    .withColumn("order_id",   col("order_id").cast(IntegerType())) \
    .withColumn("silver_load_ts", current_timestamp())

print("\n🔄 Step 3: Schema Enforcement")
for field in df_silver_final.schema.fields:
    print(f"   {field.name:20} → {field.dataType}")

# In real project:
# df_silver_final.write.format("delta").mode("append")
#     .saveAsTable("silver.sales_orders")
# df_quarantine.write.format("delta").mode("append")
#     .saveAsTable("quarantine.sales_orders")
```

---

## 🥇 STAGE 3 — Gold Aggregation + Validation

### Step 1 — Gold Aggregation

```python
print("=" * 55)
print("🥇 GOLD AGGREGATION + VALIDATION")
print("=" * 55)

df_gold = df_silver_final \
    .filter(col("status") == "COMPLETED") \
    .groupBy("region", "order_date") \
    .agg(
        spark_sum("amount").alias("total_revenue"),
        count("order_id").alias("order_count"),
        avg("amount").alias("avg_order_value")
    ) \
    .withColumn("avg_order_value", spark_round(col("avg_order_value"), 2)) \
    .withColumn("gold_load_ts", current_timestamp())

print("\n📊 Gold Aggregated Table:")
df_gold.show(truncate=False)
```

---

### Step 2 — Reconciliation Silver vs Gold

```python
# ════════════════════════════════════════════════════
# DOUBT 6: How does .collect()[0]["total"] work?
# ════════════════════════════════════════════════════
#
# Let's break it down step by step:
#
# STEP A: .filter(status == COMPLETED)
#   → Keeps only COMPLETED rows
#   → Removes PENDING (order 1003 excluded from revenue)
#
# STEP B: .agg(spark_sum("amount").alias("total"))
#   → Adds up all amount values into ONE number
#   → Returns a DataFrame with 1 row and 1 column called "total"
#   → Result: DataFrame[ Row(total=12700.0) ]
#
# STEP C: .collect()
#   → Brings data FROM Spark cluster TO Python driver
#   → Returns a Python LIST of Row objects
#   → Result: [ Row(total=12700.0) ]
#              ↑ list with 1 item inside
#
# STEP D: [0]
#   → Gets the FIRST item from the list (index 0)
#   → Result: Row(total=12700.0)
#
# STEP E: ["total"]
#   → Gets the value of column "total" from the Row
#   → Result: 12700.0  ← plain Python float!
#
# Full journey:
# DataFrame → filter → agg → collect() → [0] → ["total"] → 12700.0
# ════════════════════════════════════════════════════

silver_completed_total = df_silver_final \
    .filter(col("status") == "COMPLETED") \
    .agg(spark_sum("amount").alias("total")) \
    .collect()[0]["total"]

gold_total = df_gold \
    .agg(spark_sum("total_revenue").alias("total")) \
    .collect()[0]["total"]

# ── abs() explained ──
# Without abs():  12500 - 12700 = -200  (negative — confusing!)
# With abs():     both cases give 200   (always positive — clean!)

variance     = abs(silver_completed_total - gold_total)
variance_pct = (variance / silver_completed_total) * 100

TOLERANCE_PCT = 1.0   # Allow max 1% difference for rounding

print(f"\n🔍 Reconciliation: Silver → Gold")
print(f"   Silver COMPLETED Total : £{silver_completed_total:,.2f}")
print(f"   Gold Total Revenue     : £{gold_total:,.2f}")
print(f"   Variance               : £{variance:,.2f} ({variance_pct:.2f}%)")
print(f"   Status : {'✅ RECONCILED' if variance_pct < TOLERANCE_PCT else '🚨 MISMATCH'}")
```

---

### 💡 DOUBT 7 — Discrepancy Demo With Buggy Gold Data

```python
# ── Real Bug Scenario ──
# Gold notebook accidentally filtered out SOUTH region
# £8200 from Motor_Unit order is lost in Gold
# Reconciliation catches this!

buggy_gold_data = [
    ("NORTH", "2024-01-15", 4500.00),
    # SOUTH is MISSING → £8200 not counted!
]

buggy_gold_cols = ["region", "order_date", "total_revenue"]
df_gold_buggy   = spark.createDataFrame(buggy_gold_data, buggy_gold_cols)

print("Silver Data (COMPLETED only):")
df_silver_final.filter(col("status") == "COMPLETED").show()

print("Buggy Gold Data:")
df_gold_buggy.show()

# Run reconciliation against buggy gold
gold_total_buggy = df_gold_buggy \
    .agg(spark_sum("total_revenue").alias("total")) \
    .collect()[0]["total"]

variance_buggy     = abs(silver_completed_total - gold_total_buggy)
variance_pct_buggy = (variance_buggy / silver_completed_total) * 100

print("=" * 50)
print("🔍 RECONCILIATION REPORT — BUGGY SCENARIO")
print("=" * 50)
print(f"  Silver COMPLETED Total : £{silver_completed_total:,.2f}")
print(f"  Gold Total (Buggy)     : £{gold_total_buggy:,.2f}")
print(f"  Variance (£)           : £{variance_buggy:,.2f}")
print(f"  Variance (%)           : {variance_pct_buggy:.2f}%")
print()

if variance_pct_buggy <= TOLERANCE_PCT:
    print("✅ RECONCILIATION PASSED")
else:
    print("🚨 RECONCILIATION FAILED!")
    print(f"   Expected  : £{silver_completed_total:,.2f}")
    print(f"   Gold shows: £{gold_total_buggy:,.2f}")
    print(f"   Missing   : £{variance_buggy:,.2f}")
    print(f"   Possible causes:")
    print(f"     → Region filter bug in Gold notebook")
    print(f"     → JOIN dropped rows")
    print(f"     → NULL handling issue in aggregation")
```

### Output (Buggy Scenario):
```
==================================================
🔍 RECONCILIATION REPORT — BUGGY SCENARIO
==================================================
  Silver COMPLETED Total : £12,700.00
  Gold Total (Buggy)     : £4,500.00
  Variance (£)           : £8,200.00
  Variance (%)           : 64.57%

🚨 RECONCILIATION FAILED!
   Expected  : £12,700.00
   Gold shows : £4,500.00
   Missing   : £8,200.00
   Possible causes:
     → Region filter bug in Gold notebook
     → JOIN dropped rows
     → NULL handling issue in aggregation
```

---

### Step 3 — Anomaly Check vs Yesterday

```python
# Compare today's Gold total against yesterday
# If revenue drops 90% overnight → likely a pipeline bug
# not a real business event

yesterday_total = 14200.00   # From DQ metrics log table in real project
today_total     = gold_total
change_pct      = ((today_total - yesterday_total) / yesterday_total) * 100

THRESHOLD = 50.0   # Alert if swing > 50%

print(f"\n🔍 Anomaly Check vs Yesterday")
print(f"   Yesterday Revenue : £{yesterday_total:,.2f}")
print(f"   Today Revenue     : £{today_total:,.2f}")
print(f"   Change            : {change_pct:+.1f}%")

if abs(change_pct) > THRESHOLD:
    print(f"   🚨 ANOMALY: {abs(change_pct):.1f}% swing exceeds {THRESHOLD}% threshold!")
    print(f"   Investigate: pipeline bug? source issue? missing data?")
else:
    print(f"   ✅ Within acceptable range")
```

---

## 📋 End-to-End Pipeline Summary

```python
print("\n" + "=" * 55)
print("📋 END-TO-END PIPELINE SUMMARY")
print("=" * 55)
print(f"   Source Records Extracted  : {df_raw.count()}")
print(f"   Bronze Records Landed     : {df_bronze.count()}")
print(f"   Duplicates Removed        : {dupes_removed}")
print(f"   Quarantined Records       : {df_quarantine.count()}")
print(f"   Silver Valid Records      : {df_silver_final.count()}")
print(f"   Gold Revenue (COMPLETED)  : £{gold_total:,.2f}")
print(f"   Quarantine Rate           : {(df_quarantine.count()/df_raw.count()*100):.1f}%")
print("=" * 55)
```

### Output:
```
=======================================================
📋 END-TO-END PIPELINE SUMMARY
=======================================================
   Source Records Extracted  : 7
   Bronze Records Landed     : 7
   Duplicates Removed        : 1
   Quarantined Records       : 3
   Silver Valid Records      : 3
   Gold Revenue (COMPLETED)  : £12,700.00
   Quarantine Rate           : 42.9%
=======================================================
```

---

## 🎤 Interview Answer — Walk Me Through Data Validation

> "In our project, ADF handles extraction from SQL Server to Bronze
> in ADLS Gen2, and Databricks handles Silver and Gold processing.
>
> For Bronze — after ADF Copy Activity completes, a Databricks notebook
> is triggered via ADF Notebook Activity. It validates row count against
> ADF's rowsCopied metadata, checks critical columns for nulls, and
> confirms schema consistency using set comparison. If any check fails,
> the notebook exits with a failure code and ADF halts the pipeline
> using an If Condition activity.
>
> For Silver — the transformation notebook first deduplicates using a
> window function on business keys ordered by load timestamp. Then it
> applies business rule validation — null checks on non-nullable fields,
> range checks on amounts, valid status values. Records failing rules go
> to a quarantine Delta table with the failure reason tagged. Only clean
> records proceed to Silver.
>
> For Gold — after aggregation, we do a bottom-up reconciliation comparing
> Silver COMPLETED totals against Gold totals within a 1% tolerance. We also
> compare today's metrics against the previous day to catch anomalies like a
> sudden 90% revenue drop which would indicate a pipeline bug.
>
> During development we tested manually with sample datasets. In production,
> these checks run automatically on every pipeline execution."

---

## 🔑 Key Concepts — Quick Reference

| Concept | What It Does |
|---|---|
| `@activity('Copy').output.rowsCopied` | ADF expression to read copy row count |
| `dbutils.widgets.text("name","default")` | Declare parameter receiver in Databricks |
| `dbutils.widgets.get("name")` | Read the parameter value ADF passed |
| `dbutils.notebook.exit("SUCCESS")` | Signal ADF: validation passed |
| `dbutils.notebook.exit("FAILED")` | Signal ADF: stop pipeline |
| `raise Exception("msg")` | Simpler way to fail ADF activity |
| `set(list)` | Convert list to set for comparison |
| `actual - expected` | New columns that appeared from source |
| `expected - actual` | Missing columns dropped by source |
| `Window.partitionBy().orderBy()` | Group + sort for deduplication |
| `row_number() == 1` | Keep only latest record per group |
| `.agg(spark_sum("col"))` | Sum a column into one number |
| `.collect()` | Bring Spark result to Python as a list |
| `[0]` | Get first row from collected list |
| `["col_name"]` | Get value from Row object |
| `abs()` | Always positive — avoids negative variance |
| `variance_pct < TOLERANCE_PCT` | Check if difference is acceptable |
| `If Condition in ADF` | Branch pipeline based on notebook exit value |

---

## 📊 Doubts Covered — Checklist

```
✅ Doubt 1 — How ADF knows rowsCopied (delivery receipt concept)
✅ Doubt 2 — How to pass rowsCopied to Databricks via ADF Parameters
✅ Doubt 3 — How dbutils.widgets.text() and .get() work
✅ Doubt 4 — What set() is and how set minus (-) finds differences
✅ Doubt 5 — How to fail ADF pipeline (2 methods explained)
✅ Doubt 6 — How .collect()[0]["total"] works step by step
✅ Doubt 7 — Discrepancy demo with buggy Gold data (SOUTH missing)
✅ Doubt 8 — What abs() does and why we use it for variance
```

---
*Study Notes — E2E ETL Validation | Interview Preparation*
